# Generated by Django 5.2 on 2025-04-21 23:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LLC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the LLC", max_length=200, unique=True
                    ),
                ),
                (
                    "creation_date",
                    models.DateField(help_text="Date the LLC was officially created"),
                ),
                (
                    "last_filing_date",
                    models.DateField(
                        help_text="Date of the last required filing (e.g., annual report)"
                    ),
                ),
            ],
            options={
                "verbose_name": "LLC",
                "verbose_name_plural": "LLCs",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "street_number",
                    models.CharField(help_text="e.g., '123', '456A'", max_length=20),
                ),
                (
                    "street_name",
                    models.CharField(
                        help_text="e.g., 'Main St', 'Elm Ave Lot 5'", max_length=150
                    ),
                ),
                (
                    "date_purchased",
                    models.DateField(
                        blank=True,
                        help_text="Date the property/home was acquired",
                        null=True,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        help_text="Description of size (e.g., '14x60', 'Double Wide', '1000 sq ft')",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OCC", "Occupied"),
                            ("VAC", "Vacant"),
                            ("OFF", "Office"),
                            ("LOT", "Lot Vacant"),
                            ("OTH", "Other"),
                        ],
                        default="VAC",
                        help_text="Current status of the property",
                        max_length=3,
                    ),
                ),
                (
                    "rent_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Monthly rent amount in dollars",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "home_payment",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Monthly home mortgage/payment (if any) in dollars",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "lot_payment",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Monthly lot rent/payment (if applicable) in dollars",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "make",
                    models.CharField(
                        blank=True,
                        help_text="Manufacturer of the mobile home",
                        max_length=100,
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Year the mobile home was manufactured",
                        null=True,
                    ),
                ),
                (
                    "vin",
                    models.CharField(
                        blank=True,
                        help_text="Vehicle Identification Number (VIN) of the mobile home",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "security_deposit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Required security deposit amount in dollars",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "bedrooms",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Number of bedrooms"
                    ),
                ),
                (
                    "bathrooms",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("1.0"),
                        help_text="Number of bathrooms (e.g., 1.0, 1.5, 2.0)",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.5"))
                        ],
                    ),
                ),
                (
                    "power_provider",
                    models.CharField(
                        blank=True,
                        help_text="Name of the electric utility provider",
                        max_length=100,
                    ),
                ),
                (
                    "water_provider",
                    models.CharField(
                        blank=True,
                        help_text="Name of the water utility provider",
                        max_length=100,
                    ),
                ),
                (
                    "llc",
                    models.ForeignKey(
                        help_text="The LLC that owns this property",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="properties",
                        to="rentals.llc",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Properties",
                "ordering": ["llc", "street_number", "street_name"],
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "identification_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DL", "Driver's License"),
                            ("DOD", "DoD ID"),
                            ("SSN", "Social Security Card"),
                            ("PASS", "Passport"),
                            ("OTH", "Other"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "identification_number",
                    models.CharField(
                        blank=True,
                        help_text="Number associated with the ID type",
                        max_length=100,
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False, help_text="Has the tenant passed screening?"
                    ),
                ),
                (
                    "date_approved",
                    models.DateField(
                        blank=True, help_text="Date the tenant was approved", null=True
                    ),
                ),
                (
                    "move_in_date",
                    models.DateField(
                        blank=True,
                        help_text="Date the tenant officially moved in",
                        null=True,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        help_text="The property this tenant currently occupies (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tenants",
                        to="rentals.property",
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(help_text="Date the payment was received"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount of the payment in dollars",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes (e.g., check number, payment method, period covered)",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        help_text="The property the payment is for",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="rentals.property",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="The tenant who made the payment",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="rentals.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-payment_date", "tenant"],
            },
        ),
    ]
