# Generated by Django 5.2 on 2025-04-22 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llc",
            name="last_filing_date",
            field=models.DateField(
                blank=True,
                help_text="Date of the last required filing (e.g., annual report)",
                null=True,
            ),
        ),
    ]
